name = "cf-service-vector"
main = "src/index.js"
compatibility_date = "2024-02-23"
workers_dev = false


################################################################################
## DEV
################################################################################

[vars]
ENVIRONMENT = "dev"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "test-dev"


################################################################################
## PROD
################################################################################

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "test"
